[project]
name = "ocr-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.9",
    "pandas>=3.0.3",
    "pillow>=12.2.0",
    "pymupdf>=1.27.2.3",
    "pytesseract>=0.3.13",
    "requests>=2.34.2",
    "seaborn>=0.13.2",
]

[project.scripts]
"main.py" = "main:main"
